// Trips
export const LOAD_TRIPS_REQUEST = 'LOAD_TRIPS_REQUEST'
export const LOAD_TRIPS_SUCCESS = 'LOAD_TRIPS_SUCCESS'
export const LOAD_TRIPS_FAILURE = 'LOAD_TRIPS_FAILURE'

// Single Trip
export const LOAD_TRIP_REQUEST = 'LOAD_TRIP_REQUEST'
export const LOAD_TRIP_SUCCESS = 'LOAD_TRIP_SUCCESS'
export const LOAD_TRIP_FAILURE = 'LOAD_TRIP_FAILURE'
